# Generated by Django 4.2.3 on 2023-10-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_planilhafinal_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilhafinal',
            name='mes',
        ),
    ]
